---
title: "clean_alcohol_data"
output: 
  html_document:
    df_print: paged
    keep_md: yes
    toc: yes
---

###Introduction

tba

##Goal

tba

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Libraries

-- Load Library for reading CSV Files.

```{r eval=FALSE, echo=TRUE}
library(csvread)
library(tidyr)
```

### Read raw data

```{r eval=TRUE, echo=TRUE}
alcoholdata_raw <- read.csv(file ="../data/raw_data/alcohol_consumption.csv", header = TRUE)
alcoholdata_raw


```
Characterisics of raw data  
number of columns:  

```{r eval=TRUE, echo=TRUE}
ncol(alcoholdata_raw)
```
number of rows:  

```{r eval=TRUE, echo=TRUE}
nrow(alcoholdata_raw)
```

###Clean raw data
-- Renaming columns
-- Omit superfluous columns: X1: "Datasource", Years 2016 & 2010-2014

```{r eval=TRUE, echo=TRUE}
names(alcoholdata_raw)
names(alcoholdata_raw)[1]<- "Country"
names(alcoholdata_raw)[2]<- "data_source"
names(alcoholdata_raw)[3]<- "Beverage_Types"
names(alcoholdata_raw)[4]<- "Alcohol_per_capita_2016"
names(alcoholdata_raw)[5]<- "Alcohol_per_capita_2015"
names(alcoholdata_raw)[6]<- "Alcohol_per_capita_2014"
names(alcoholdata_raw)[7]<- "Alcohol_per_capita_2013"
names(alcoholdata_raw)[8]<- "Alcohol_per_capita_2012"
names(alcoholdata_raw)[9]<- "Alcohol_per_capita_2011"
names(alcoholdata_raw)[10]<- "Alcohol_per_capita_2010"

drops<- c("data_source","Alcohol_per_capita_2016","Alcohol_per_capita_2014","Alcohol_per_capita_2013","Alcohol_per_capita_2012","Alcohol_per_capita_2011","Alcohol_per_capita_2010")
alcoholdata_2015_only <- alcoholdata_raw[, !names(alcoholdata_raw) %in% drops]
alcoholdata_2015_only 

```

-- Reordering of row/columns: One row for one country, Beverage Types as single columns
```{r eval=TRUE, echo=TRUE}
#delete first row
alcoholdata_2015_only<- alcoholdata_2015_only[-c(1), ]
alcoholdata_2015_only

```


--Clearing out NAs
```{r eval=TRUE, echo=TRUE}
nrow(alcoholdata_2015_only)
alcoholdata_clean <- na.omit(alcoholdata_2015_only)
alcoholdata_clean
nrow(alcoholdata_clean)

```
--Joining Subsets
```{r eval=TRUE, echo=TRUE}

alcoholdata_clean <- spread(alcoholdata_clean, Beverage_Types, Alcohol_per_capita_2015)
alcoholdata_clean
nrow(alcoholdata_clean)

```
--Write into CSV

```{r eval=TRUE, echo=TRUE}
write.csv(alcoholdata_clean, file = "../data/clean_data/alcohol_data.csv",row.names=FALSE, na="", col.names = TRUE)

```

