---
title: "Clean Happiness Data"
output:
  html_document:
    df_print: paged
    keep_md: yes
---
## Clean Happiness Record

### Setup

#### Read raw data

```{r eval=TRUE, echo=TRUE}
dfHappiness.raw <- read.csv(file = "../data/raw_data/world_happiness_report_2015.csv", header = TRUE)
dfHappiness.raw
```

### Clean Data

-- Delete the rank column, as it will be incorrect when later merging all studies, because some countries will be dropped.

```{r eval=TRUE, echo=TRUE}
dfHappiness.raw[3] <- NULL
```

-- Renaming columns

```{r eval=TRUE, echo=TRUE}
names(dfHappiness.raw)[3]<- "Happiness.Score"
names(dfHappiness.raw)[4]<- "Happiness.Score.Standard.Error"
names(dfHappiness.raw)[5]<- "Economy.GDP.per.Capita"
names(dfHappiness.raw)[6]<- "Family"
names(dfHappiness.raw)[7]<- "Health.Life.Expectancy"
names(dfHappiness.raw)[8]<- "Freedom"
names(dfHappiness.raw)[9]<- "Trust.Government.Corruption"
names(dfHappiness.raw)[10]<- "Generosity"
names(dfHappiness.raw)[11]<- "Dystopia.Residual"
```

-- rename Countries

```{r eval=TRUE, echo=TRUE}

ind <- which(levels(dfHappiness.raw$Country)=="Republic of Korea", arr.in=TRUE)
levels(dfHappiness.raw$Country)[ind] <- "North Korea"

ind <- which(levels(dfHappiness.raw$Country)=="Russia", arr.in=TRUE)
levels(dfHappiness.raw$Country)[ind] <- "Russian Federation"

dfHappiness.clean <- dfHappiness.raw
dfHappiness.clean
```

-- Write into CSV

```{r eval=TRUE, echo=TRUE}
write.csv(dfHappiness.clean, file = "../data/clean_data/happiness_data.csv",row.names=FALSE, na="", col.names = TRUE)

```